version: '3.8'

networks:
  mapper-cluster-network:
    name: mapper-cluster-network

services:
  mapper-mongo-1:
    image: mongo:4.2
    container_name: mapper-mongo-1
    ports:
      - "27017:27017"
    networks:
      - mapper-cluster-network
    command:
      - --replSet
      - mapper-mongo-set

  mapper-mongo-2:
    image: mongo:4.2
    container_name: mapper-mongo-2
    ports:
      - "27018:27017"
    networks:
      - mapper-cluster-network
    command:
      - --replSet
      - mapper-mongo-set

  mapper-mongo-3:
    image: mongo:4.2
    container_name: mapper-mongo-3
    ports:
      - "27019:27017"
    networks:
      - mapper-cluster-network
    command:
      - --replSet
      - mapper-mongo-set
