version: '3.4'

networks:
  mapper-cluster-network:

services:
  mapper-mongo-1:
    image: mongo:4.2
    container_name: mapper-mongo-1
    ports:
      - "27017:27017"
    networks:
      - mapper-cluster-network
    command:
      - --replSet
      - mapper-mongo-set

  mapper-mongo-2:
    image: mongo:4.2
    container_name: mapper-mongo-2
    ports:
      - "27018:27017"
    networks:
      - mapper-cluster-network
    command:
      - --replSet
      - mapper-mongo-set

  mapper-mongo-3:
    image: mongo:4.2
    container_name: mapper-mongo-3
    ports:
      - "27019:27017"
    networks:
      - mapper-cluster-network
    command:
      - --replSet
      - mapper-mongo-set

  mapper:
    container_name: mapper
    image: jembi/openhim-mediator-mapping:latest
    environment:
      - MONGO_URL='mongodb://mapper-mongo-1:27017,mapper-mongo-2:27017,mapper-mongo-3:27017/mapping-mediator?replicaSet=mapper-mongo-set'
      - OPENHIM_REGISTER=false
    ports:
      - "3003:3003"
    networks:
      - mapper-cluster-network
    depends_on:
      - mapper-mongo-1
      - mapper-mongo-2
      - mapper-mongo-3
